version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entered the install phase..
      - apt-get update -y
      - apt-get update -y maven
    finally:
      - echo always runs even if the update or install command fails  
      
    pre-build:
      commands:
       - echo entered the pre-build phase
      finally:
        - echo this is always run if command fails
      
service:
 provider:
  name: aws
  runtime: Java 8 on Amazon Linux 1
  region: ap-south-1
  
  
 functions:
  LambdaDemo1:
    handler: LambdaDemo1.handler
    
  Sample:
    handler: Sample.handler
          
  build:
    commands:
    - echo "Build started"
    - mnv install
    
  finally:
      - echo always runs even if th install command fails  
 
  post_build:
    commands:
    - echo "Build completed"
   
artifacts:
  artifact1:
    files:
    - target/LambdaDemo1-0.0.1-SNAPSHOT.jar
    discard-paths: yes
  artifact2:
    files:
    - target/Sample-0.0.1-SNAPSHOT.jar
    discard-paths: yes
    
    
 
  